# System Health Check — $env:TIMESTAMP
# Auto-generated by Hermes cron job (hourly, Kuwait time)

$ErrorActionPreference = 'Stop'
$timestamp = Get-Date -Format 'yyyyMMdd_HHmm'
$reportLines = @()
$alerts = @()
$warnings = @()

function Add-Report {
    param([string]$Line)
    $reportLines += $Line
    Write-Output $Line
}

# --- 1. Docker daemon ---
try {
    $dockerOut = docker ps --format '{{.Names}}' 2>&1
    if ($LASTEXITCODE -ne 0) { throw "docker ps failed: $dockerOut" }
    $containers = ($dockerOut.Trim() -split '\r?\n') | Where-Object { $_.Trim() -ne '' }
    $msg = "[DOCKER] OK — $($containers.Count) container(s) running"
    if ($containers.Count -gt 0) { $msg += ": $($containers -join ', ')" }
    Add-Report $msg
    if ($containers.Count -eq 0) { $warnings += "No containers running (daemon OK)" }
} catch {
    $msg = "[DOCKER] DOWN — $($_.Exception.Message)"
    Add-Report $msg
    $alerts += $msg
    try {
        Start-Service -Name com.docker.service -ErrorAction Stop
        Start-Sleep -Seconds 5
        $verify = docker ps --format '{{.Names}}' 2>&1
        if ($LASTEXITCODE -eq 0) {
            Add-Report "[DOCKER] Restarted successfully"
        } else {
            $msg = "[DOCKER] Restart failed — manual intervention required"
            Add-Report $msg
            $alerts += $msg
        }
    } catch {
        $msg = "[DOCKER] Restart failed: $($_.Exception.Message) — manual intervention required"
        Add-Report $msg
        $alerts += $msg
    }
}

# --- 2. RAM ---
try {
    $os = Get-CimInstance Win32_OperatingSystem
    $totalGB = [math]::Round($os.TotalVisibleMemorySize / 1MB, 2)
    $freeMB = [math]::Round($os.FreePhysicalMemory / 1KB, 1)
    $pct = [math]::Round($os.FreePhysicalMemory / $os.TotalVisibleMemorySize * 100, 1)
    $status = if ($freeMB -gt 500) { 'OK' } else { 'LOW' }
    Add-Report "[RAM] $status — $freeMB MB free ($pct%) / $totalGB GB total"
    if ($freeMB -le 500) {
        $alerts += "RAM free ($freeMB MB) <= 500 MB threshold"
    }
} catch {
    Add-Report "[RAM] ERROR — $($_.Exception.Message)"
    $alerts += "RAM check failed"
}

# --- 3. Hermes agents ---
try {
    $hermesProcs = Get-Process -Name 'hermes*' -ErrorAction SilentlyContinue
    $nodeProcs = Get-Process -Name 'node' -ErrorAction SilentlyContinue
    $pythonProcs = Get-Process -Name 'python' -ErrorAction SilentlyContinue
    $total = @($hermesProcs + $nodeProcs + $pythonProcs | Where-Object {
        $_.MainWindowTitle -ne '' -or
        ($_.CommandLine -match 'hermes|agent' -and $_.CommandLine) -or
        $_.Name -match '^hermes'
    }) | Select-Object Id, Name, CPU, WorkingSet -First 15
    $count = $total.Count
    if ($count -gt 0) {
        Add-Report "[AGENTS] OK — $count Hermes-related process(es) found"
        $total | ForEach-Object {
            $memMB = [math]::Round($_.WorkingSet / 1KB, 1)
            $cpu = [math]::Round($_.CPU, 1)
            Add-Report "  PID=$($_.Id) $($_.Name) CPU=$cpu% RAM=$memMB MB"
        }
    } else {
        Add-Report "[AGENTS] None detected — verify Hermes is running"
        $alerts += "No Hermes agent processes found"
    }
} catch {
    Add-Report "[AGENTS] ERROR — $($_.Exception.Message)"
    $alerts += "Agent check failed"
}

# --- 4. Disk C: ---
try {
    $disk = Get-CimInstance Win32_LogicalDisk -Filter 'DeviceID="C:"' -ErrorAction Stop
    $totalGB = [math]::Round($disk.Size / 1GB, 2)
    $freeGB = [math]::Round($disk.FreeSpace / 1GB, 2)
    $freePct = [math]::Round(($disk.FreeSpace / $disk.Size) * 100, 1)
    $status = if ($freePct -gt 10) { 'OK' } elseif ($freePct -gt 5) { 'LOW' } else { 'CRITICAL' }
    Add-Report "[DISK C:] $status — $freeGB GB free ($freePct%) / $totalGB GB total"
    if ($freePct -le 10) {
        $alerts += "Disk C: free space ($freePct%) <= 10% threshold"
    }
} catch {
    Add-Report "[DISK] ERROR — $($_.Exception.Message)"
    $alerts += "Disk check failed"
}

# --- 5. Git alforaijboard ---
$gitDir = 'C:/Users/hello/alforaijboard-gh'
try {
    Push-Location $gitDir
    $statusOut = git status --porcelain 2>&1
    if ($LASTEXITCODE -ne 0) { throw "git status failed: $statusOut" }
    $dirty = ($statusOut.Trim() -split '\r?\n') | Where-Object { $_.Trim() -ne '' }
    if ($dirty.Count -gt 0) {
        Add-Report "[GIT] DIRTY — $($dirty.Count) uncommitted change(s):"
        $dirty | ForEach-Object { Add-Report "  $_" }
        $alerts += "Git repo has $($dirty.Count) uncommitted change(s)"
    } else {
        Add-Report "[GIT] CLEAN — no uncommitted changes"
    }
} catch {
    Add-Report "[GIT] ERROR — $($_.Exception.Message)"
    $alerts += "Git check failed"
} finally {
    Pop-Location
}

# --- Summary ---
$alertCount = $alerts.Count
$warnCount = $warnings.Count
if ($alertCount -gt 0) {
    $reportLines += ""
    $reportLines += "!!! $($alertCount + $warnCount) ISSUE(S): $alertCount alert(s), $warnCount warning(s)"
    $alerts | ForEach-Object { $reportLines += "  ! $_" }
    $warnings | ForEach-Object { $reportLines += "  ~ $_" }
} else {
    $reportLines += ""
    $reportLines += "All systems nominal. $warnCount minor warning(s)."
}

# --- Push to Supabase ---
$supabaseUrl = 'https://bwspcsiazbwrrxpgoldx.supabase.co/rest/v1/cron_results'
$anongKey = $env:SUPABASE_ANON_KEY
if ($anongKey -and $anongKey.Length -gt 10) {
    $payload = @{
        name = "health_check_$timestamp"
        status = if ($alertCount -gt 0) { 'error' } else { 'success' }
        message = ($reportLines -join "`n")
        duration_ms = $null
        records_affected = $null
        created_at = $timestamp
    } | ConvertTo-Json -Compress
    try {
        $headers = @{
            'Content-Type' = 'application/json'
            'apikey'       = $anongKey
            'Authorization'= "Bearer $anongKey"
        }
        $response = Invoke-WebRequest -Uri $supabaseUrl -Method Post -Headers $headers -Body $payload -UseBasicParsing
        if ($response.StatusCode -eq 201 -or $response.StatusCode -eq 200) {
            $reportLines += ""
            $reportLines += "[DB] Result pushed to Supabase cron_results (HTTP $($response.StatusCode))"
        } else {
            $reportLines += ""
            $reportLines += "[DB] Supabase returned HTTP $($response.StatusCode)"
        }
    } catch {
        $reportLines += ""
        $reportLines += "[DB] Supabase push failed (non-fatal): $($_.Exception.Message)"
    }
} else {
    $reportLines += ""
    $reportLines += "[DB] SUPABASE_ANON_KEY not set — skipping push"
}

return ($reportLines -join "`n")
