#!/usr/bin/env python3
"""
Rebuild health report from latest raw checks + push to Supabase.

Reads the _cron_health_latest.json generated by health_cron_run.sh
(push_health_to_supabase.py consumed it but didn't transform it correctly),
then normalizes the structure and pushes to Supabase cron_results table.
"""
import json
import sys
import urllib.request
import urllib.error
from datetime import datetime, timezone

# --- Config ---
PROJECT_REF = "bwspcsiazbwrrxpgoldx"
TABLE_NAME = "cron_results"

# Read API key: file first, then env
KEY_FILE = "/c/Users/hello/alforaijboard-gh/supabase_data/supabase_key.txt"
API_KEY = None
if __import__("os").path.exists(KEY_FILE):
    with open(KEY_FILE) as f:
        API_KEY = f.read().strip()
if not API_KEY:
    API_KEY = __import__("os").environ.get("SUPABASE_ANON_KEY") or __import__("os").environ.get("SUPABASE_SERVICE_KEY")
if not API_KEY:
    print("ERROR: No Supabase API key found.")
    print(f"  Tried file: {KEY_FILE}")
    print("  Tried env vars: SUPABASE_ANON_KEY, SUPABASE_SERVICE_KEY")
    sys.exit(1)

# --- Load latest raw health report ---
REPORT_PATH = "/c/Users/hello/alforaijboard-gh/_cron_health_latest.json"
try:
    with open(REPORT_PATH) as f:
        raw = json.load(f)
except Exception as e:
    print(f"ERROR: Cannot read {REPORT_PATH}: {e}")
    sys.exit(1)

# --- Normalize check results into a flat row ---
checks = raw.get("checks", {})

def get_check(name, key, default=""):
    c = checks.get(name, {})
    return c.get(key, default) if isinstance(c, dict) else default

docker_status = get_check("docker", "status", "UNKNOWN")
docker_msg = get_check("docker", "msg", "") or get_check("docker", "error", "") or "No detail"

ram_status = get_check("ram", "status", "UNKNOWN")
ram_free_mb = checks.get("ram", {}).get("free_mb", 0) if isinstance(checks.get("ram"), dict) else 0
ram_msg = get_check("ram", "msg", "") or f"{ram_free_mb}MB free"

agents_status = "OK" if get_check("agents", "count", 0) >= 0 else "UNKNOWN"
agents_count = get_check("agents", "count", 0)
agents_procs = get_check("agents", "procs", "")

disk_status = get_check("disk", "status", "UNKNOWN")
disk_free = get_check("disk", "free", "")
disk_use_pct = get_check("disk", "use_pct", 0)
disk_msg = get_check("disk", "msg", "")

git_status = get_check("git", "status", "UNKNOWN")
git_dirty_count = get_check("git", "dirty_count", 0)
git_msg = get_check("git", "msg", "")

# Count alerts: anything not OK/clean
alert_keys = {
    "docker": docker_status,
    "ram": ram_status,
    "disk": disk_status,
    "git": git_status,
}
alerts_count = sum(1 for v in alert_keys.values() if v not in ("OK", "clean"))
overall_status = "ok" if alerts_count == 0 else "error"

row = {
    "created_at": datetime.now(timezone.utc).isoformat(),
    "timestamp": raw.get("timestamp", datetime.now().strftime("%Y%m%d_%H%M")),
    "docker_status": docker_status,
    "docker_msg": docker_msg,
    "ram_status": ram_status,
    "ram_free_mb": ram_free_mb,
    "ram_msg": ram_msg,
    "agents_status": agents_status,
    "agents_count": agents_count,
    "agents_procs": agents_procs,
    "disk_status": disk_status,
    "disk_free": disk_free,
    "disk_use_pct": disk_use_pct,
    "disk_msg": disk_msg,
    "git_status": git_status,
    "git_dirty_count": git_dirty_count,
    "git_msg": git_msg,
    "summary": f"{docker_status}|{ram_status}|{disk_status}|{git_status}",
    "status": overall_status,
    "alerts": alerts_count,
}

print("=== Normalized health row ===")
print(json.dumps(row, indent=2))

# --- Push to Supabase ---
url = f"https://{PROJECT_REF}.supabase.co/rest/v1/{TABLE_NAME}"
headers = {
    "Content-Type": "application/json",
    "apikey": API_KEY,
    "Prefer": "return=minimal",
}
data = json.dumps(row).encode("utf-8")
req = urllib.request.Request(url, data=data, headers=headers, method="POST")

try:
    with urllib.request.urlopen(req, timeout=30) as resp:
        body = resp.read().decode("utf-8")
        code = resp.status
        print(f"\nHTTP {code}: {body}")
        if code == 201:
            print("\n✓ Health check saved to Supabase cron_results!")
        else:
            print(f"\n⚠ Unexpected status {code}")
except urllib.error.HTTPError as e:
    print(f"\nHTTP Error {e.code}: {e.reason}")
    print(e.read().decode("utf-8", errors="replace"))
    sys.exit(1)
except urllib.error.URLError as e:
    print(f"\nURL Error: {e.reason}")
    sys.exit(1)
